### ISSUE TITLE
websocket_server panics when `--wsallinterfaces` is supplied without any other arguments.

### ISSUE THREAD

**Issue by NZSmartie** [intiface/intiface-cli-rs#10]
In my attempts to test the btleplug/buttplug libraries, I grabbed this project to try to quickly get myself up and running.
I've currently got ca76f78 (v23) and I've modified the `Cargo.toml` to use a local development copy of buttplug-rs as well as a local development copy of btleplug.

## Expected behaviour

Running `cargo run -- --wsallinterfaces` would sping up an insecure Intiface server to test with uing default ports that is commonly associated with Intiface (12345, 12346)

## Actual Behaviour

```
main' panicked at 'assertion failed: !ret.inner.is_empty()', /home/nzsmartie/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/select_all.rs:40:5
```

This happens in:
buttplug-rs panics in `buttplug-rs/buttplug/src/connector/transport/websocket/websocket_server.rs`::`impl ButtplugConnectorTransport for ButtplugWebsocketServerTransport`::`connect()`

```rust
    Box::pin(async move {
      *disconnect_sender.lock().await = request_sender.clone();
      if let Err(connector_err) = select_all(tasks).await.0 {
        Err(connector_err)
      } else {
        Ok((request_sender, response_receiver))
      }
    })
```

`select_all` asserts that `tasks` is not empty. However, since neither the port for an insecure websocket or secure websocket was provided, no websocket future tasks were added to `tasks`. causing the assertion to trigger.

**Comment by NZSmartie** [comment]
Would it be a good idea for Intiface to assume default port numbers? or should arguments be checked before attempting to listen on any websocket port

**Comment by NZSmartie** [comment]
Similarly, `buttplug-rs` should also check for an empty `tasks` and fail gracefully. Though I will open a separate issue there

**Comment by qdot** [comment]
Fixed in v25
