### ISSUE TITLE
Does not install on Ubuntu 22.04 LTS.

### ISSUE THREAD

**Issue by x-mara-weber-x** [intiface/intiface-cli-rs#17]
Using `rustup` and the default toolchain:

`cargo +stable-x86_64-unknown-linux-gnu install intiface-cli`

ultimately fails with

```
   Compiling git2 v0.15.0
   Compiling intiface-cli v50.0.0
error: failed to run custom build command for `intiface-cli v50.0.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installi2JrcJ/release/build/intiface-cli-8cd53a1f867a084a/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: could not find repository from '/home/natalie/.cargo/registry/src/github.com-1ecc6299db9ec823/intiface-cli-50.0.0'; class=Repository (6); code=NotFound (-3)', /home/natalie/.cargo/registry/src/github.com-1ecc6299db9ec823/intiface-cli-50.0.0/build.rs:9:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

Interestingly it does succeed if I clone this repo and do a cargo build instead. So maybe this is something about how this package is published?

It would be good if it could be installed directly, since the released binaries don't work well on linux. There are too many different configurations and I can't get it to work on Ubuntu 22.04 without rebuilding it locally. There is a hack for making libssl.so.1.1 work there but it will kinda mess up the system.

**Comment by qdot** [comment]
This project is deprecated, but I forgot to update the readme and archive it. You'll want to try https://github.com/intiface/intiface-engine now.
